django_auth_adfs-1.11.5.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
django_auth_adfs-1.11.5.dist-info/LICENSE,sha256=n3ImkhGUnnJEu1sT51QKc_N22WdixSRcrfg9gj6nr3c,1296
django_auth_adfs-1.11.5.dist-info/METADATA,sha256=L2CsKBB8f2QYng6FvTiKDVrwIOYwT5Je1s4cOcv3baw,6305
django_auth_adfs-1.11.5.dist-info/RECORD,,
django_auth_adfs-1.11.5.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_auth_adfs-1.11.5.dist-info/WHEEL,sha256=7Z8_27uaHI_UZAc4Uox4PpBhQ9Y5_modZXWMxtUi4NU,88
django_auth_adfs/__init__.py,sha256=vvinReQ530z7PGktsPFHHJ9Uup-RPzrI9rMkeD_oFeQ,137
django_auth_adfs/__pycache__/__init__.cpython-39.pyc,,
django_auth_adfs/__pycache__/backend.cpython-39.pyc,,
django_auth_adfs/__pycache__/config.cpython-39.pyc,,
django_auth_adfs/__pycache__/drf-urls.cpython-39.pyc,,
django_auth_adfs/__pycache__/drf_urls.cpython-39.pyc,,
django_auth_adfs/__pycache__/exceptions.cpython-39.pyc,,
django_auth_adfs/__pycache__/middleware.cpython-39.pyc,,
django_auth_adfs/__pycache__/rest_framework.cpython-39.pyc,,
django_auth_adfs/__pycache__/signals.cpython-39.pyc,,
django_auth_adfs/__pycache__/urls.cpython-39.pyc,,
django_auth_adfs/__pycache__/views.cpython-39.pyc,,
django_auth_adfs/backend.py,sha256=UxKnlMrQ3IMOnIiBd3itYtFOer-QxLTSHXXt5deew-s,18055
django_auth_adfs/config.py,sha256=p9uNhl4C6OIuiUHAdYmW6LiqhvoI_ZnR_W-mh-u3Z6w,16251
django_auth_adfs/drf-urls.py,sha256=bBnN1WrgbHoiAs5hTGe-ovmVwwJ4D2xXpYtZVfE8l5U,221
django_auth_adfs/drf_urls.py,sha256=YKH7he1cCDr_eo0kgPJQiJ3kmo1FBS46JzSiBOOqwE0,430
django_auth_adfs/exceptions.py,sha256=yxwKHtDSMnskgBdIQoCWerYVr8sGtIn26GWVVdhA2YU,110
django_auth_adfs/middleware.py,sha256=st8Hx5pHWNcYUNWrCQht3QJqjw6RLQhWyxneTWal0Nw,2249
django_auth_adfs/rest_framework.py,sha256=spWIXpb8UtVDvZ0_W_sJB-5u0hwvLNUCqbAhHf9N0W4,1656
django_auth_adfs/signals.py,sha256=HGD79-dZNEwqVuINoqe6jB_8K1RfuK5Q288RGamTtEU,137
django_auth_adfs/templates/django_auth_adfs/login_failed.html,sha256=1NQ5aCjo7iTLSxy2IXJZbzBp5MaxpfsfQwQ_PDFvgr4,652
django_auth_adfs/urls.py,sha256=4Cec5XbxrAqPHc_N3yMTC_m9UKZXsZktf3rO2niF4Bw,533
django_auth_adfs/views.py,sha256=kwMqcsDAgcuQRBgxpRVnFZY79ZkVo28LB3KOIbayI3E,4100
